version: "2"

services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
#      - 'es_data: /usr/share/elasticsearch/data'

  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
    ports:
      - "5000:5000" # tcp
      - "8021:8021" # http
      - "5044:5044" # beats
    links:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    links:
      - elasticsearch


volumes:
  es-data: